# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       hawaii-icon-theme

# >> macros
# << macros

Summary:    Icon themes for Hawaii desktop environment
Version:    0.2.0
Release:    1
Group:      System/X11/Icons
License:    CC-BY-SA and GPLv2 and LGPLv2
BuildArch:  noarch
URL:        https://github.com/mauios/hawaii-icon-themes.git
Source0:    hawaii-icon-theme-%{version}.tar.xz
Source100:  hawaii-icon-theme.yaml
Requires(post): /bin/touch
Requires(post): %{_bindir}/gtk-update-icon-cache
BuildRequires:  cmake

%description
This is an icon-theme for Hawaii desktop environment.

%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
# << build pre

%cmake .  \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%post
/bin/touch --no-create %{_datadir}/icons/hicolor || :
%{_bindir}/gtk-update-icon-cache \
  --quiet %{_datadir}/icons/hicolor 2> /dev/null|| :

%postun
/bin/touch --no-create %{_datadir}/icons/hicolor || :
%{_bindir}/gtk-update-icon-cache \
  --quiet %{_datadir}/icons/hicolor 2> /dev/null|| :

%files
%defattr(-,root,root,-)
%{_datadir}/icons/elegant/
%{_datadir}/icons/hawaii/
# >> files
# << files
