# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       hawaii-icon-theme

# >> macros
# << macros

Summary:    Hawaii Icon Style package
Version:    0.1.90.20130724.d9ceaeb
Release:    1
Group:      Applications/System
License:    BSD
Source0:    icon-themes-%{version}.tar.bz2
Source100:  hawaii-icon-theme.yaml
Requires(post): /bin/touch
Requires(post): %{_bindir}/gtk-update-icon-cache
BuildRequires:  cmake
#BuildRequires:  vibe-devel

%description
Package provides Hawaii desktop icons


%prep
%setup -q -n icon-themes

# >> setup
# << setup

%build
# >> build pre
# << build pre

%cmake .  \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DCMAKE_INSTALL_PREFIX=/usr

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post


%post
/bin/touch --no-create %{_datadir}/icons/hicolor || :
%{_bindir}/gtk-update-icon-cache \
  --quiet %{_datadir}/icons/hicolor 2> /dev/null|| :

%postun
/bin/touch --no-create %{_datadir}/icons/hicolor || :
%{_bindir}/gtk-update-icon-cache \
  --quiet %{_datadir}/icons/hicolor 2> /dev/null|| :

%files
%defattr(-,root,root,-)
%{_datadir}/icons/elegant/
# >> files
# << files
